name: Test

on: [push, pull_request]

permissions:
  contents: read

jobs:
  ruby-versions:
    uses: ruby/actions/.github/workflows/ruby_versions.yml@master
    with:
      min_version: 2.3
      engine: cruby-jruby
      
  test:
    needs: ruby-versions
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ 'ubuntu-latest' ]
        ruby: ${{ fromJson(needs.ruby-versions.outputs.versions) }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Install dependencies
      run: bundle install
    - name: Run tests
      run: bundle exec rake test
